### ISSUE TITLE
err

### ISSUE THREAD

**Issue by hezhenyuqwq** [morpheuslord/WinFiHack#11]
__        ___       _____ _ _   _            _
\ \      / (_)_ __ |  ___(_) | | | __ _  ___| | __
 \ \ /\ / /| | '_ \| |_  | | |_| |/ _` |/ __| |/ /
  \ V  V / | | | | |  _| | |  _  | (_| | (__|   <
   \_/\_/  |_|_| |_|_|   |_|_| |_|\__,_|\___|_|\_\

       Main Menu
┏━━━━━┳━━━━━━━━━━━━━━━┓
┃ OPT ┃ NAME          ┃
┡━━━━━╇━━━━━━━━━━━━━━━┩
│ 1   │ Set Interface │
│ 2   │ Set Target    │
│ 3   │ Set Wordlist  │
│ 4   │ Show Options  │
│ 5   │ Run Attack    │
│ q   │ Quit          │
└─────┴───────────────┘
Enter Option: 2
Exception in thread Thread-5 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\32463\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\32463\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\32463\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1568, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 3867: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\32463\Desktop\WinFiHack-main\main.py", line 387, in <module>
    networks_json = wifi_manager.run()
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\32463\Desktop\WinFiHack-main\main.py", line 335, in run
    self.run()
  File "C:\Users\32463\Desktop\WinFiHack-main\main.py", line 337, in run
    self.get_wifi_networks()
  File "C:\Users\32463\Desktop\WinFiHack-main\main.py", line 57, in get_wifi_networks
    lines = result.stdout.split("\n")
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

C:\Users\32463\Desktop\WinFiHack-main>

**Comment by morpheuslord** [comment]
Will look into it 👍
